apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    component: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
    backstage.io/kubernetes-id: nationalparks-py
    backstage.io/kubernetes-namespace: div
    quay.io/repository-slug: divyanshiGupta/nationalparks-py,
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
