apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    backstage.io/kubernetes-id: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
spec:
  type: service
  lifecycle: unknown
  owner: default
